#cloud-config
users: # user wird definiert
  - name: ubuntu # name des benutzers
    sudo: ALL=(ALL) NOPASSWD:ALL # sudo-Regeln für diesen Benutzer
    groups: users, admin # gruppe des benutzers
    home: /home/ubuntu # pfad vom user
    shell: /bin/bash # pfad vom shell
    ssh_authorized_keys: # ssh key des users
      - ssh-rsa key-0ddedab44aa0408b6
ssh_pwauth: false # passwort-deaktiviertung ausgeschaltet
disable_root: false # root user deaktivieren
package_update: true # package sollen updated werden
packages: # angegebene packages werden installiert
  - curl
  - wget
